### ISSUE TITLE
missed to publish v0.6.0 to npm

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/en-route#2]

**Comment by doowb** [comment]
Thanks for pointing this out. I'll get it published soon.

**Comment by jonschlinkert** [comment]
I think there was a reason I didn't publish to npm yet. @doowb if you want to just do a review and publish that's fine.

**Comment by doowb** [comment]
Looks like 0.6.0 had been removed. 0.7.0 is up there now.
