### ISSUE TITLE
Dynamically add methods

### ISSUE THREAD

**Issue by doowb** [jonschlinkert/en-route#3]
Expose a way to dynamically add methods:

```
var router = new Router({
  methods: ['one', 'two', 'three']
});
router.method('four');
router.method(['five', 'six']);
```

I think that's all that the api needs to look like.
Then internally, I think the new methods are unioned `this.methods` and decorated onto the router.

**Comment by jonschlinkert** [comment]
maybe it should be called `handler`? so doing `router.handler('foo')` adds a method.
