### ISSUE TITLE
allow to optionally use `file.relative` instead of `file.path` when matching

### ISSUE THREAD

**Issue by doowb** [jonschlinkert/en-route#7]
In the [code here](https://github.com/jonschlinkert/en-route/blob/master/lib/layer.js#L28), the matching is done against `file.path`. I'd like to be able to choose to match against `file.relative`.

Do you have any ideas on how we could configure this? Maybe an optional function that's passed through to `Layer` that's used there.

By doing this it will allow us to write middleware handlers like this:

```js
app.onLoad('posts/:post/:index*', (view, params) => {
  console.log(params);

  //=> file path => /path/to/files/posts/post-1/index.hbs
  //=> { post: 'post-1', index: 'index.hbs' }

  //=> file path => /path/to/files/posts/create.hbs
  //=> { post: 'create.hbs', index: undefined }
});
```

**Comment by jonschlinkert** [comment]
> By doing this it will allow us to write middleware handlers like this:

Versus what? What does it do now?

**Comment by jonschlinkert** [comment]
fwiw, to do what you want all you have to do is:

```js
router.onLoad('(.*)/posts/:post/:index*', (file, params) => {
  console.log(params) //=> { '0': '/path/to/files', post: 'post-1', index: 'index.hbs' }
});
```

**Comment by doowb** [comment]
The patterns that you point out aren't something I thought of. That will work instead of adding additional support for something else. Thanks.
